spring.application.name=ms_bootcamp_tecnologia
server.port=8081

# Configuración MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/TECHNOLOGY?serverZoneId=America%2FBogota
spring.r2dbc.username=root
spring.r2dbc.password=root

# Ejecutar scripts de inicialización
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

jwt.secret=EstaEsUnaClaveSuperSeguraDeAlMenos32Caracteres
