CREATE TABLE IF NOT EXISTS TECHNOLOGY.TECHNOLOGY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(90) NOT NULL
);

CREATE TABLE IF NOT EXISTS TECHNOLOGY.CAPACITY_TECHNOLOGY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_technology BIGINT NOT NULL,
    id_capacity BIGINT NOT NULL,
    UNIQUE KEY uq_technology_capacity (id_technology, id_capacity)
);

